-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 11:16:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homeinventorydb` ;

-- -----------------------------------------------------
-- Schema homeinventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeinventorydb` DEFAULT CHARACTER SET latin1 ;
USE `homeinventorydb` ;

-- -----------------------------------------------------
-- Table `homeinventorydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`users` (
  `Username` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `First_Name` VARCHAR(50) NOT NULL,
  `Last_Name` VARCHAR(50) NOT NULL,
  `Active` BIT NOT NULL,
  `Is_Admin` BIT NOT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`categories` (
  `categoryid` INT NOT NULL AUTO_INCREMENT,
  `Category_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoryid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `homeinventorydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeinventorydb`.`items` (
  `itemid` INT NOT NULL AUTO_INCREMENT,
  `categoryid` INT NOT NULL,
  `Item_Name` VARCHAR(45) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Owner` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`itemid`),
  INDEX `fk_items_Categories_idx` (`categoryid` ASC),
  INDEX `fk_items_users1_idx` (`Owner` ASC),
  CONSTRAINT `fk_items_Categories`
    FOREIGN KEY (`categoryid`)
    REFERENCES `homeinventorydb`.`categories` (`categoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`Owner`)
    REFERENCES `homeinventorydb`.`users` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

